version: '2'

services:
  node:
    image: thejmazz/etcd:v3.3.1
    environment:
      - ETCD_DISCOVERY=${ETCD_DISCOVERY}
    entrypoint: /bin/sh
    command: >
      -c "etcd
      --name $$(hostname)
      --initial-advertise-peer-urls http://$$(hostname -i):2380
      --listen-peer-urls http://$$(hostname -i):2380
      --listen-client-urls http://$$(hostname -i):2379,http://127.0.0.1:2379
      --advertise-client-urls http://$$(hostname -i):2379"
    labels:
      io.rancher.scheduler.affinity:host_label_soft: etcd=true
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name

  lb:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
      - 2379:2379/tcp
