version: '2'

catalog:
  name: etcd-ha
  version: v3.3.1

  questions:
    - variable: ETCD_DISCOVERY
      type: string
      required: true
      label: ETCD_DISCOVERY
      description: "https://discovery.etcd.io/new?size=SCALE"
    - variable: SCALE
      type: int
      required: true
      label: SCALE
      description: etcd cluster size, should be odd, tolerates up to (N-1)/2 permanent failures
      default: 3

services:
  etcd:
    scale: ${SCALE}
    retain_ip: true
    health_check:
      port: 2379
      request_line: ''
      # request_line: GET /health HTTP/1.1
      interval: 5000
      response_timeout: 3000
      unhealthy_threshold: 2
      healthy_threshold: 2

  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
        - priority: 1
          protocol: http
          service: etcd
          source_port: 2379
          target_port: 2379
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
