version: '2'

catalog:
  name: etcd-ha
  version: v3.2.9-1

  questions:
    - variable: ETCD_DISCOVERY
      type: string
      required: true
      label: ETCD_DISCOVERY
      description: "https://discovery.etcd.io/new?size=3"

services:
  etcd:
    health_check:
      port: 2378
      request_line: /health
      interval: 5000
      response_timeout: 3000
      unhealthy_threshold: 2
      healthy_threshold: 2
