version: '2'

catalog:
  name: etcd-ha
  version: v3.2.9-1

  questions:
    - variable: ETCD_DISCOVERY
      type: string
      required: true
      label: ETCD_DISCOVERY
      description: "https://discovery.etcd.io/new?size=3"

