version: '2'

catalog:
  name: etcd-ha
  version: v3.2.9-1

  questions:
    - variable: ETCD_DISCOVERY
      type: string
      required: true
      label: ETCD_DISCOVERY
      description: "https://discovery.etcd.io/new?size=SCALE"
    - variable: SCALE
      type: int
      required: true
      label: SCALE
      description: etcd cluster size, should be odd, tolerates up to (N-1)/2 permanent failures
      default: 3

services:
  etcd:
    scale: ${SCALE}
    retain_ip: true
    health_check:
      port: 2379
      request_line: ''
      # request_line: GET /health HTTP/1.1
      interval: 5000
      response_timeout: 3000
      unhealthy_threshold: 2
      healthy_threshold: 2
